#!/bin/bash

VENV=".venv"

python3 -m venv $VENV
source $VENV/bin/activate

function install_dependencies {
    python3 -m pip install -r requirements.txt --no-cache-dir
}

python3 app.py $@ || (install_dependencies && python3 app.py $@)
deactivate
